### ISSUE TITLE
Errror findOne

### ISSUE THREAD

**Issue by k-yuriy** [Sammaye/mongoyii-php7#12]
Hello! The method findOne in class Document does not work correctly. 
![4332c1660a](https://cloud.githubusercontent.com/assets/5803264/18083787/21d629c4-6ebe-11e6-90e0-ba8ff37999b6.jpg)

**Comment by Sammaye** [comment]
How so?

**Comment by k-yuriy** [comment]
In line 819 you should merge $query with the $filter. But now, in $query you have dbCriteria and 
you merge $query this $this->getDbCriteria() again.

**Comment by Sammaye** [comment]
So I do, thanks, I see it now. Gonna need a bit of work since this is replicated in most read functions

**Comment by k-yuriy** [comment]
you'r welcome =) good luck!
