### ISSUE TITLE
Problem with multidatabase application.

### ISSUE THREAD

**Issue by Kuzdo** [Sammaye/mongoyii-php7#17]
Hi!

I have problem when in one Action I'm using few DBs. One DB I have set as default (active) in main.php, in Model I have specified getCollection method with second DB. And now the best: application counts records from good (second) DB, but is trying retrieving records from default DB:
```
2016-12-29T12:29:00.071+0100 I COMMAND  [conn1] command db2.$cmd command: count { count: "some_collection", limit: 0, skip: 0 } planSummary: COUNT ntoreturn:1 keyUpdates:0 writeConflicts:0 numYields:0 reslen:44 locks:{ Global: { acquireCount: { r: 2 } }, MMAPV1Journal: { acquireCount: { r: 1 } }, Database: { acquireCount: { r: 1 } }, Collection: { acquireCount: { R: 1 } } } 0ms
2016-12-29T12:29:00.074+0100 I QUERY    [conn1] query db1.some_collection query: { $query: {}, $orderby: { _id: 1 } } planSummary: EOF ntoreturn:20 ntoskip:0 nscanned:0 nscannedObjects:0 keyUpdates:0 writeConflicts:0 numYields:0 nreturned:0 reslen:20 locks:{ Global: { acquireCount: { r: 2 } }, MMAPV1Journal: { acquireCount: { r: 1 } }, Database: { acquireCount: { r: 1 } }, Collection: { acquireCount: { R: 1 } } } 0ms
```

@Sammaye , can you check why this happens?

**Comment by Kuzdo** [comment]
Ok, I found were is problem. [Query->getDb()](../blob/master/Query.php#L332-L335) is selecting default DB instead correct... But I don't know how to fix it.

**Comment by Sammaye** [comment]
If I remember right it selects what currently active.

I did do something in the readme about using multiple DBs

**Comment by Kuzdo** [comment]
So, I should change active DB when I want perform query to another DB? This can't be done automatically?

**Comment by Sammaye** [comment]
Aha, actually this is a bug. It should be adding the DB name param to https://github.com/Sammaye/mongoyii-php7/blob/master/Query.php#L334 select database here

**Comment by Kuzdo** [comment]
I thought so

**Comment by Sammaye** [comment]
One way to do this is to go:
```
$db = Yii::app()->mogno->selectDatabase('otherdatabase');
Query()->db = $db;
```

**Comment by Sammaye** [comment]
But really it should be able to use the DB that is actually provided within the query initially

**Comment by Sammaye** [comment]
Actually scratch that first comment lol, since the line does a selectdatabase it will still default back

**Comment by Sammaye** [comment]
One really hacky way is that selectDatabase in the client lets you change the default https://github.com/Sammaye/mongoyii-php7/blob/master/Client.php#L218 but this neds fixing

**Comment by Kuzdo** [comment]
I was thinking to add db name param to [$query->all()](../blob/master/Document.php#L895) in Document.php

**Comment by Sammaye** [comment]
Are you querying two different dbs on the same model?

**Comment by Kuzdo** [comment]
No, in one Model i use one DB, but in one Action i have CGridView to few DBs

**Comment by Sammaye** [comment]
I would be more tempted to fix this directly in the Query model then on that line I quoted. When it does selectDatabase it is running a piece of code which links to https://github.com/Sammaye/mongoyii-php7/blob/master/Client.php#L218 which means it only selects the default database and not the one you supply to the Query.

**Comment by Kuzdo** [comment]
Please check if that fix is ok: #18

**Comment by Sammaye** [comment]
Ah yes, so you use the code I use in the readme to change the source for the model. Problem is the model may not always be there so this code will only work for one specific scenario.

Half of my thought is:

```
public function setDb($db)
{
    self::$db = $db
}
```

Then you can just do:

    (new Query)->db(Yii::app()->mognodb->selectDatabase('omg2'))->...

That should cover all bases. It is a bit clunky I know but it will be compatible with all methods. Maybe there is a cleaner way you can think of?

But that's a quick thought in between of other thoughts. What do you think?

**Comment by Sammaye** [comment]
Hmm, that still won't work actually, hmm

**Comment by Sammaye** [comment]
Ok, could make a new property which contains the db object and getDb() checks that db object first and returns it else returns default. That way query can be used anywhere

**Comment by Kuzdo** [comment]
Idk how are you want to use this code, I have view with CGridView and where I should put this:
```(new Query)->db(Yii::app()->mognodb->selectDatabase('omg2'))->...``` ?

**Comment by Sammaye** [comment]
What is the full code of your grid view?

**Comment by Kuzdo** [comment]
```php
    $this->widget('zii.widgets.grid.CGridView', array(
        'id'           => 'model-grid',
        'dataProvider' => $dataProvider->search(),
        'formatter'    => new CustomFormatter(),
        'columns'      => $columns,
        'ajaxUpdate'   => false
    ));
```

**Comment by Sammaye** [comment]
Ok, you wouldn't use the code I showed there sicne you're using active record to populate the gridviews.

Basically the query can be used with or without active record, basically on it's own as well.

**Comment by Kuzdo** [comment]
Hello in 2017!

Do you have an idea how to solve this? I really need to make it work.

**Comment by Sammaye** [comment]
Sorry for being absent, I am so busy with projects right now that all the issues on here are just getting older

**Comment by Sammaye** [comment]
Just do your pull request for the min, when I get a chance I will make something better which should be compatible with current code

**Comment by Kuzdo** [comment]
I wrote another patch which should be better than previous one. Check this #19

**Comment by Sammaye** [comment]
That's good. There is another way as well, we change the DB object in the Query object to actually be a DB, this way selectDatabase will never be run since it is never needed

**Comment by Sammaye** [comment]
Since, of course, we have to think with and without active record

**Comment by Sammaye** [comment]
Ah no, I use the DBConnection direct in the query, hmm this needs a lot of thought.

I would still recommend you apply a personal patch that works for your situation and I really need some time to think about this

**Comment by Sammaye** [comment]
Remember to add something for one() as well

**Comment by Sammaye** [comment]
oh NVM, queryInternal does that

**Comment by Kuzdo** [comment]
Yea, for now this works for me, but I know that this isn't perfect solution.

**Comment by Sammaye** [comment]
It isn't but this needs some serious thought and I haven't touched this ext in too long so I need to find spare time to actually sit down a remember where everything is

**Comment by Sammaye** [comment]
right, back to this one... hmmm

**Comment by Sammaye** [comment]
Ok, so a little think later and I am thinking of changing Query.php getDb() to something like:

```php
	public function getDb()
	{
		$name = $this->databaseName;
		if($this->model){
			// Get DB nam from model
			$name = $this->model->getCollection()->database->getDatabaseName();
		}
		
		// Will select default database if name is null
		return $this->getDbConnection()->selectDatabase($name);
	}
```

This will make db selection invisible for 99% of cases and allow a person to actually override the DB directly is they want to.

What do you think?

**Comment by Sammaye** [comment]
This is the full proposal https://github.com/Sammaye/mongoyii-php7/commit/dd5363e61e061ccbaab889f74a84e0acf48e9d17 let me know what you think

**Comment by Kuzdo** [comment]
I'm using my fix from #19 and this is working.
Your code returns an error:
```
Undefined property: MongoDB\Collection::$database (C:\xampp\htdocs\my-project\protected\vendor\sammaye\mongoyii-php7\Query.php:352)
```

**Comment by Sammaye** [comment]
Hmm it shouldn't now that I fixed the __get() hmm

**Comment by Kuzdo** [comment]
Ahh, ok, my mistake

**Comment by Kuzdo** [comment]
I downloaded latest version from your repo and didn't work.

**Comment by Sammaye** [comment]
Ok I will test in a sec, I must admit I did this just before going lunch

**Comment by Kuzdo** [comment]
No problem :)

**Comment by Kuzdo** [comment]
```
Undefined property: sammaye\mongoyii\Collection::$database (C:\xampp\htdocs\my-project\protected\vendor\sammaye\mongoyii-php7\Query.php:352)
```

**Comment by Sammaye** [comment]
Ah yeah, of course

**Comment by Sammaye** [comment]
Still untested since I have not had a chance but this should fix it https://github.com/Sammaye/mongoyii-php7/commit/cbed71c86e84e3349483d6c54e049ec9449f400d

**Comment by Sammaye** [comment]
Ok tested without active record

**Comment by Kuzdo** [comment]
Sorry for late response. Yes, this commit is fixes previous problem :D Thank you!

**Comment by Kuzdo** [comment]
Can you create new release that I could update extension via composer?

**Comment by Sammaye** [comment]
Awesome I'm gonna release this then!

**Comment by Sammaye** [comment]
Hehe thinking same thing there :P

**Comment by Kuzdo** [comment]
Thanks!

**Comment by Sammaye** [comment]
Pushed to 2.0.0 since this change is slightly BC breaking for some scenarios https://github.com/Sammaye/mongoyii-php7/releases/tag/2.0.0
