### ISSUE TITLE
CLI application

### ISSUE THREAD

**Issue by Kuzdo** [Sammaye/mongoyii-php7#22]
How I should import this extension in CLI application? In webapp I added to index.php:
```php
$loader        = require(__DIR__ . '/protected/vendor/autoload.php');
Yii::$classMap = $loader->getClassMap();
```
before
```php
Yii::createWebApplication($config)->run();
```
and all is working.
For now I added this code to console.php config before `return array(*config*);` but I don't know if it is good solution?

**Comment by Sammaye** [comment]
As far as I can think you would do it exactly as how it is done in the main application (or backend/frontend) the console app should support the same autoloader

**Comment by Kuzdo** [comment]
But in console app, there are no index.php, there is only yiic.php where is included yiic.php from framework dir (and there is Yii::createConsoleApplication), so I can't add this code before "require" and if I add code after "require" there is no effect, because application is started already.

**Comment by Sammaye** [comment]
And if you take out the require entirely it cannot read your vendor directory?

**Comment by Sammaye** [comment]
I also noticed you have your vendors in a weird location, in my test app I have clearly in the root of the application on `/`

**Comment by Kuzdo** [comment]
When we started the project we were starting the adventure with Yii and project was generated in wrong way. We created project like ```path\to\yii\framework> yiic webapp ..\```, so now we have protected folder and other in one place with framework folder:
```
root/
    assets/
    css/
    framework/
    images/
    protected/
        vendor/              there are extensions from composer
    themes/
    etc./
```

**Comment by Sammaye** [comment]
Interesting, actually going through the Yii1 source code I now see that it never loads vendors, which means what you are dong is right

**Comment by Sammaye** [comment]
Even checking the latest release, yiic never actually includes vendor folder :\

**Comment by Sammaye** [comment]
Ok I remember now, in my test app I manually entered:

    require_once(dirname(__FILE__) . '/vendor/autoload.php');

I have forgotten Yii1 a lot lol. Anyway that is how I do stuff

**Comment by Kuzdo** [comment]
Ohh, ok. I will use it in console app, but in webapp I will leave the code from first comment.

**Comment by Sammaye** [comment]
Should be ok so long as you don't define your own classmap in the config, else it will overwrite

**Comment by Kuzdo** [comment]
I'm not using classmap in config, so it's ok :)

**Comment by Sammaye** [comment]
Awesome, I still do sometimes since older Yii1 exts still don't sit on composer.

I will close this now since this seems clarified and solved

**Comment by Sammaye** [comment]
For future reference for me, adding:

    require_once(dirname(dirname(__FILE__)) . '/vendor/autoload.php');

to `yiic.php` works just fine
