### ISSUE TITLE
findAndModify didn't work

### ISSUE THREAD

**Issue by Kuzdo** [Sammaye/mongoyii-php7#23]
When I call
```php
Model::model()->getCollection()->findAndModify(...)
```
I got a error:
```
Error: Call to undefined method MongoDB\Collection::findAndModify() in C:\xampp\htdocs\project\protected\commands\CronCommand.php:27
Stack trace:
#0 [internal function]: CronCommand->actionRunReceive()
#1 C:\xampp\htdocs\project\framework\console\CConsoleCommand.php(172): ReflectionMethod->invokeArgs(Object(CronCommand), Array)
#2 C:\xampp\htdocs\project\framework\console\CConsoleCommandRunner.php(71): CConsoleCommand->run(Array)
#3 C:\xampp\htdocs\project\framework\console\CConsoleApplication.php(92): CConsoleCommandRunner->run(Array)
#4 C:\xampp\htdocs\project\framework\base\CApplication.php(185): CConsoleApplication->processRequest()
#5 C:\xampp\htdocs\project\framework\yiic.php(33): CApplication->run()
#6 C:\xampp\htdocs\project\protected\yiic.php(7): require_once('C:\\xampp\\htdocs...')
#7 {main}
```
I don't know why here is not used Collection from this extension... Can you check this?

**Comment by Sammaye** [comment]
Fascinating that is saying the PHPLib for MongoDB is not loaded into your applicaton

**Comment by Sammaye** [comment]
Specifically this file https://github.com/mongodb/mongo-php-library/blob/master/src/Collection.php

**Comment by Sammaye** [comment]
Do you have a separate composer for your main app and your console app?

**Comment by Kuzdo** [comment]
No, I have only one composer for vendor dir.

**Comment by Kuzdo** [comment]
And this error is both in console and main app. No matter where I used findAndModify, everywhere this reports error.

**Comment by Sammaye** [comment]
Ok that narrows it down, that functions has been removed from the PHPLib

**Comment by Kuzdo** [comment]
In PHPLib are 3 functions that are doing the same what was doing findAndModify in mongo driver: findOneAndDelete, findOneAndUpdate, findOneAndReplace.

**Comment by Sammaye** [comment]
Hang on I see it now, I coded this in the collection and used findandmodify for all three

**Comment by Sammaye** [comment]
Ok here is the problem https://github.com/Sammaye/mongoyii-php7/blob/master/Database.php#L24

It is using the client's __get which it shouldn't.

Hmm, I really need to find time to fix this ext

**Comment by Sammaye** [comment]
It should really be `return $this->selectCollection($this->database->__get($collectionName));` or something

**Comment by Sammaye** [comment]
Or not that actually, but it needs to return a Collection object

**Comment by Kuzdo** [comment]
Maybe ```return $this->selectCollection($collectionName);``` ? This is working for me for now...

**Comment by Sammaye** [comment]
Ah yeah, I missed you can just do that, sorry I am at work while sorting this lol

**Comment by Kuzdo** [comment]
I'm also at work. And we are using yours extensions (previous one MongoYii and this from now) in our project, so I'm truly grateful for your work :)

**Comment by Sammaye** [comment]
Thanks :) I will get round to fixing this code, I just took on a few freelance projects so my time is split atm

**Comment by Kuzdo** [comment]
No problem :)

**Comment by Sammaye** [comment]
https://github.com/Sammaye/mongoyii-php7/commit/3573bda1e8360e8e3967538a2f1d6063f587a2bc
