### ISSUE TITLE
findAndModify returns MongoDB\BSON\BSONDocument instead of Model class

### ISSUE THREAD

**Issue by Kuzdo** [Sammaye/mongoyii-php7#24]
How can I change this behaviour?

**Comment by Sammaye** [comment]
Really hard since I cannot guarantee the return type of findAndModify

**Comment by Sammaye** [comment]
So, I actually left this up to the user to do since it is application dependent

**Comment by Kuzdo** [comment]
Can I put into model a method that will be returns the result as a that model?

Maybe typeMaps? I found [here][1] that:

> TypeMaps can be set through the MongoDB\Driver\Cursor::setTypeMap() method on a MongoDB\Driver\Cursor object, or the $typeMap argument of MongoDB\BSON\toPHP(). Each of the three classes (root, document and array) can be individually set.
>
> If the value in the map is NULL, it means the same as the default value for that item.

But Idk how use it in model...

[1]: https://secure.php.net/manual/en/mongodb.persistence.deserialization.php

**Comment by Sammaye** [comment]
Type maps require a specific interface and if I remember right they are not automatically compatible with Yii2, not only that but last I checked the only way to actually get any docs on type maps was to look at the description for them in the PHPLib docs

**Comment by Sammaye** [comment]
Ok so it seems they added some documentation and it could work.

findAndModify does not return a cursor but it is worth a try

**Comment by Kuzdo** [comment]
So, how I should try to do this?

**Comment by Sammaye** [comment]
Hmm, I am (yet again) a bit busy so I cannot jump onto my test application
and test this out.

First you need to figure out what findAndModify is returning, I think it
just returns an array.

Once done you could make a function in your models to transpose this array
into the model.

I think this is best left out of the ext itself since this is very much
scenario dependent on how you use findAndModify and what params you provide
it

**Comment by Kuzdo** [comment]
Like I wrote in topic, findAndModify returns MongoDB\BSON\BSONDocument

**Comment by Sammaye** [comment]
Oh you have verified that? Okay, I have also checked this out, it does use a cursor: https://github.com/mongodb/mongo-php-library/blob/master/src/Operation/FindAndModify.php#L183 so using typemaps directly shold just work actually

**Comment by Kuzdo** [comment]
Ok, I found one solution:
```php
 (new Model)->populateRecord($findAndModifyResult);
```
but idk if this will not interfere with something else... For now is working, but findAndModify definitely should return Model object

**Comment by Sammaye** [comment]
Not as good as using typemaps since you apply one object to another (technically using a tiny bit more memory and processing speed) but that's a very reasonable solution

**Comment by Kuzdo** [comment]
This is only used in console app, and code is very simple, so it's ok :D

**Comment by Sammaye** [comment]
Hehe then yep, that's a good solution.

I will close this now, if anything else comes up feel free to reopen
