### ISSUE TITLE
"Call to undefined function sammaye\mongoyii\bson_encode()"

### ISSUE THREAD

**Issue by Kuzdo** [Sammaye/mongoyii-php7#25]
When I want use $model->getBSONDocument() I got error:
`Call to undefined function sammaye\mongoyii\bson_encode()` in [Model.php#L700](../blob/master/Model.php#L700).

This function is wrong, because bson_encode only exists in mongo driver, not mongodb, or I don't know about something.

**Comment by Sammaye** [comment]
It is a driver only function but specifically of the previous driver.

Since this function is probably only used by you I forgot to amend it

**Comment by Sammaye** [comment]
Quick untested fix: https://github.com/Sammaye/mongoyii-php7/commit/a0ccfb62992f68105c8e52867d444ce864f4a5ec

**Comment by Sammaye** [comment]
How is it going with this? I still have not had a chance to test

**Comment by Sammaye** [comment]
I added another commit too which fixes the namespace rsolution

**Comment by Kuzdo** [comment]
Ok,  now is ok :)
