### ISSUE TITLE
How can I change the _id field in document?

### ISSUE THREAD

**Issue by Kuzdo** [Sammaye/mongoyii-php7#26]
Like in topic, how can I change the _id field in document? I have this code:
```php
$model->attributes = $request->getParam('Model');
if($model->save()) { ... }
```
but when I try to change _id field, that field is removed from $set array in [Document][1], and I get error:
```Modifiers operate on fields but we found a Array instead. For example: {$mod: {<field>: ...}} not {$set: []}```
because there was only _id changed, so array is empty...

When I try to comment that line, I noticed, that _id is with new value, so in update command to MongoDB can't be provided correct _id value for search pattern.
This is log from mongod.log, I was changing _id from 1 to 2:
```update database.collection query: { _id: 2 } update: { $set: { _id: 2 } }```

[1]:https://github.com/Sammaye/mongoyii-php7/blob/master/Document.php#L685

**Comment by Sammaye** [comment]
This is actually MongoDB itself, it won't allow this

**Comment by Kuzdo** [comment]
Ok, thanks.
