### ISSUE TITLE
mongoyii-php7 install as extension on Yii1.1 support

### ISSUE THREAD

**Issue by YanKawaYu** [Sammaye/mongoyii-php7#28]
Hi guys,
I'm using Yii1.1 framework with php7, so I need to install mongoyii-php7 on Yii1.1 framework as an extension. 
I know that you don't recommend this, but I can't migrate my code to Yii2 right now.
Could you please give me some guide on how to do this?
Thank you very much!

**Comment by Sammaye** [comment]
It has the same install steps as any extension, but they are described well in the old extensions documentation http://www.sammaye.com/MongoYii/

**Comment by YanKawaYu** [comment]
I finally got it done through using Yii1.1 framework with composer, and installed mongoyii-php7 through composer too. 
Thank you all the same.

**Comment by shenadmin** [comment]
> 
Hello, finally, did you install this package by installing composer? I also encountered the same problem, but the code production environment does not allow this
