### ISSUE TITLE
Parameter to cast Query->compare

### ISSUE THREAD

**Issue by ghost** [Sammaye/mongoyii-php7#32]
Hi. I've found there's no casting mechanism to Query::compare method, so a compound parameter (Say '>=0.17' is always treating '0.17' as string, and therefor a float column in MongoDb is never return)

Adding a parameter `$cast` to compare and

`switch($cast){
	case 'float':
		$value=(float)$value;
break;
...
			}`

Seems to work decently

https://github.com/jrobles-boom/mongoyii-php7/commit/fe75ce6773afd1b5fea7d2f46d54c321c6937a51

**Comment by Sammaye** [comment]
Ok, I see the real problem, there is no test for floats, a test needs to be added here to check for float as well as int https://github.com/Sammaye/mongoyii-php7/blob/master/Query.php#L385

**Comment by Sammaye** [comment]
https://github.com/Sammaye/mongoyii-php7/pull/33
