### ISSUE TITLE
Yii FrameWork 1.1, Mongo 3.2 Storage WT and driver mongodb 1.1.6

### ISSUE THREAD

**Issue by FredericoSFerreira** [Sammaye/mongoyii-php7#4]
I'm using version 1.1 with YiiFramework MongoYii this repository https://github.com/Sammaye/MongoYii, however we need to update the application to mongo 3.2 just to use JOIN feature and the new storage engine wired Tiger the current driver and 1.6 mongo, which is working perfectly except some problems with high consumption of memory, anyway update the driver for the mongodb 1.1.6 to use the features of 3.2 JOIN, there generated the problem as issue `#264` `https://github.com/Sammaye/MongoYii/issues/264`, I saw the solution in this repository, I wonder if the mongoyii-php7 runs in yii 1.1? The migration will be laborious, and we'll have to rewrite a lot of code? Excuse me for grammar, because the text was translated.

**Comment by Sammaye** [comment]
Yep this is fully compat, I am guessing you used mongofill right? I didn't even bother with it, I knew from just looking at it's source code that it would never work in a proper site

**Comment by Sammaye** [comment]
There is a fair amount that needs converting but it is a good thing, trust me, the objects in the new driver are much better than the old ones, except for UTCDateTime which requires all input to be *1000 for milisecond

**Comment by Sammaye** [comment]
Going to close this now, feel free to reopen if you need more or make a new issue for a new question
